//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string CompanyName { get; set; }
        public string PositionCompany { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime EndingDate { get; set; }
        public string Qualifications { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
